[package]
name = "blockchain"
version = "0.1.0"
authors = ["Emulebest <igorkorotach@gmail.com>"]

[dependencies]
rust-crypto = "^0.2"
chrono = { version = "^0.4", features = ["serde"] }
serde = "1.0.45"
serde_derive = "1.0"
serde_json = "1.0"
actix = "0.5"
actix-web = "0.5"
futures = "0.2.1"